# Generated by Django 2.2.6 on 2019-11-29 19:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('savings_account', models.CharField(default='Savings', max_length=25)),
                ('current_account', models.CharField(default='Current', max_length=25)),
                ('current_balance', models.IntegerField(default=500)),
                ('savings_balance', models.IntegerField(default=500)),
                ('mobile_number', models.CharField(max_length=25, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=25)),
                ('loan_amount', models.IntegerField()),
                ('loan_period', models.IntegerField()),
                ('loan_installments', models.IntegerField(blank=True, null=True)),
                ('loan_final_amount', models.IntegerField(blank=True, null=True)),
                ('loan_taker', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(max_length=150)),
                ('complaint_issuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(max_length=25)),
                ('bill_amount', models.IntegerField()),
                ('bill_paid_date', models.DateTimeField(default=datetime.datetime(2019, 11, 29, 19, 6, 52, 383227, tzinfo=utc))),
                ('bill_payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
