# Generated by Django 2.2.6 on 2019-12-01 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20191130_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_paid_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 18, 53, 34, 86958, tzinfo=utc)),
        ),
    ]
