# Generated by Django 2.2.6 on 2019-12-01 19:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20191202_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_paid_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 19, 44, 6, 173406, tzinfo=utc)),
        ),
    ]
