# Generated by Django 2.2.6 on 2019-12-01 19:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20191202_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_paid_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 1, 19, 51, 46, 272965, tzinfo=utc)),
        ),
    ]
