# Generated by Django 2.2.6 on 2019-12-30 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20191202_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_paid_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 8, 43, 43, 105300, tzinfo=utc)),
        ),
    ]
