# Generated by Django 2.2.6 on 2020-05-27 00:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20200527_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_paid_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 0, 7, 9, 860211, tzinfo=utc)),
        ),
    ]
