# Generated by Django 2.2.6 on 2020-06-04 01:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20200527_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_paid_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 1, 21, 51, 282213, tzinfo=utc)),
        ),
    ]
