# Generated by Django 2.2.6 on 2020-06-04 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20200604_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_paid_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 4, 1, 23, 2, 787918, tzinfo=utc)),
        ),
    ]
