# Generated by Django 2.2.6 on 2019-12-01 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=25)),
                ('branch_address', models.TextField()),
                ('branch_country', models.CharField(max_length=25)),
                ('branch_city', models.CharField(max_length=25)),
                ('branch_contact', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=25)),
                ('bank_head_office', models.TextField()),
                ('bank_uan', models.CharField(max_length=25)),
                ('branches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.Branch')),
            ],
        ),
    ]
